repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
        - id: check-added-large-files
        - id: debug-statements
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: check-ast
        - id: check-builtin-literals
        - id: detect-private-key
        - id: mixed-line-ending


    # reorder Python imports
    - repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
        - id: isort
          args: [ '--profile', 'black', --line-length=79 ]

#    # format Python code with black
    - repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
        - id: black
          args: [ --line-length=79 ]
          language_version: python3.10

    # check for compliant Python 3.10 code
    - repo: https://github.com/asottile/pyupgrade
      rev: v3.1.0
      hooks:
          - id: pyupgrade
            args: [ --py310-plus ]

    # code style with flake8
    - repo: https://github.com/pycqa/flake8
      rev: 5.0.4
      hooks:
          - id: flake8

    # security issues check with bandit
    - repo: https://github.com/pycqa/bandit/
      rev: 1.7.4
      hooks:
        - id: bandit
          files: 'backend/'
          exclude: 'test_*.py|tests|example'
          args: [ -ll ]

#    - repo: https://github.com/pre-commit/mirrors-mypy
#      rev: v0.982
#      hooks:
#        - id: mypy
#          additional_dependencies:
#            [
#              pydantic,
#              types-freezegun,
#              types-paramiko,
#              types-python-dateutil,
#              types-pytz,
#              types-PyYAML,
#              types-pyOpenSSL,
#              types-tzlocal,
#            ]
#          exclude: ^(test/)


exclude: env
fail_fast: true
